title: Matias Vilaplana Stark
description: >-
  Matias Vilaplana Stark is a composer and technologist.
url: ""
markdown: kramdown
# baseurl: "/"

defaults:
  -
    values:
      layout: "default"

collections:
  works:
    output: true